"""initial schema

Revision ID: 1a2b614f8a40
Revises: 
Create Date: 2026-03-27 10:24:25.423354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b614f8a40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- quotes ---
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("symbol", sa.String(128), nullable=False),
        sa.Column("mid_price", sa.Numeric(18, 8), nullable=False),
        sa.Column("reservation_price", sa.Numeric(18, 8), nullable=False),
        sa.Column("bid_price", sa.Numeric(18, 8), nullable=False),
        sa.Column("ask_price", sa.Numeric(18, 8), nullable=False),
        sa.Column("spread", sa.Numeric(18, 8), nullable=False),
        sa.Column("inventory", sa.Numeric(18, 8), nullable=False),
        sa.Column("sigma_sq", sa.Numeric(18, 8), nullable=False),
        sa.Column("gamma", sa.Numeric(18, 8), nullable=False),
        sa.Column("t_minus_t", sa.Numeric(18, 8), nullable=False),
    )
    op.create_index("ix_quotes_timestamp", "quotes", ["timestamp"])
    op.create_index("ix_quotes_symbol", "quotes", ["symbol"])
    op.create_index("ix_quotes_symbol_timestamp", "quotes", ["symbol", "timestamp"])

    # --- orders ---
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("symbol", sa.String(128), nullable=False),
        sa.Column("gemini_order_id", sa.BigInteger, nullable=False),
        sa.Column("side", sa.String(16), nullable=False),
        sa.Column("outcome", sa.String(8), nullable=False),
        sa.Column("price", sa.Numeric(18, 8), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("fill_price", sa.Numeric(18, 8), nullable=True),
    )
    op.create_index("ix_orders_timestamp", "orders", ["timestamp"])
    op.create_index("ix_orders_symbol", "orders", ["symbol"])
    op.create_index("ix_orders_gemini_order_id", "orders", ["gemini_order_id"])

    # --- positions ---
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("symbol", sa.String(128), nullable=False),
        sa.Column("yes_quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("no_quantity", sa.Numeric(18, 8), nullable=False),
        sa.Column("net_inventory", sa.Numeric(18, 8), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(18, 8), nullable=False),
    )
    op.create_index("ix_positions_timestamp", "positions", ["timestamp"])
    op.create_index("ix_positions_symbol", "positions", ["symbol"])
    op.create_index("ix_positions_symbol_timestamp", "positions", ["symbol", "timestamp"])

    # --- pnl_snapshots ---
    op.create_table(
        "pnl_snapshots",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("total_realized_pnl", sa.Numeric(18, 8), nullable=False),
        sa.Column("total_unrealized_pnl", sa.Numeric(18, 8), nullable=False),
        sa.Column("total_exposure", sa.Numeric(18, 8), nullable=False),
        sa.Column("num_active_markets", sa.Integer, nullable=False),
    )
    op.create_index("ix_pnl_snapshots_timestamp", "pnl_snapshots", ["timestamp"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_pnl_snapshots_timestamp", table_name="pnl_snapshots")
    op.drop_table("pnl_snapshots")

    op.drop_index("ix_positions_symbol_timestamp", table_name="positions")
    op.drop_index("ix_positions_symbol", table_name="positions")
    op.drop_index("ix_positions_timestamp", table_name="positions")
    op.drop_table("positions")

    op.drop_index("ix_orders_gemini_order_id", table_name="orders")
    op.drop_index("ix_orders_symbol", table_name="orders")
    op.drop_index("ix_orders_timestamp", table_name="orders")
    op.drop_table("orders")

    op.drop_index("ix_quotes_symbol_timestamp", table_name="quotes")
    op.drop_index("ix_quotes_symbol", table_name="quotes")
    op.drop_index("ix_quotes_timestamp", table_name="quotes")
    op.drop_table("quotes")

    # ### end Alembic commands ###
