"""add performative market making tables

Revision ID: 328e8391fe77
Revises: 1a2b614f8a40
Create Date: 2026-03-27 10:25:09.498655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328e8391fe77'
down_revision: Union[str, Sequence[str], None] = '1a2b614f8a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Add performative columns to quotes ---
    op.add_column("quotes", sa.Column("xi", sa.Numeric(18, 8), nullable=True))
    op.add_column("quotes", sa.Column("theta0", sa.Numeric(18, 8), nullable=True))
    op.add_column("quotes", sa.Column("theta1", sa.Numeric(18, 8), nullable=True))
    op.add_column("quotes", sa.Column("theta2", sa.Numeric(18, 8), nullable=True))
    op.add_column("quotes", sa.Column("quoting_mode", sa.String(16), nullable=True))

    # --- theta_parameters ---
    op.create_table(
        "theta_parameters",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("category", sa.String(64), nullable=False, unique=True),
        sa.Column("theta0", sa.Numeric(18, 8), nullable=False),
        sa.Column("theta1", sa.Numeric(18, 8), nullable=False),
        sa.Column("theta2", sa.Numeric(18, 8), nullable=False),
        sa.Column("xi_value", sa.Numeric(18, 8), nullable=False),
        sa.Column("objective_value", sa.Numeric(18, 8), nullable=False),
        sa.Column("num_trials", sa.Integer, nullable=False),
        sa.Column("optimized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- xi_estimates ---
    op.create_table(
        "xi_estimates",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("symbol", sa.String(128), nullable=False),
        sa.Column("xi", sa.Numeric(18, 8), nullable=False),
        sa.Column("r_squared", sa.Numeric(18, 8), nullable=True),
        sa.Column("num_trades", sa.Integer, nullable=False),
        sa.Column("used_default", sa.Boolean, nullable=False, server_default=sa.text("false")),
    )
    op.create_index("ix_xi_estimates_timestamp", "xi_estimates", ["timestamp"])
    op.create_index("ix_xi_estimates_symbol", "xi_estimates", ["symbol"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_xi_estimates_symbol", table_name="xi_estimates")
    op.drop_index("ix_xi_estimates_timestamp", table_name="xi_estimates")
    op.drop_table("xi_estimates")

    op.drop_table("theta_parameters")

    op.drop_column("quotes", "quoting_mode")
    op.drop_column("quotes", "theta2")
    op.drop_column("quotes", "theta1")
    op.drop_column("quotes", "theta0")
    op.drop_column("quotes", "xi")

    # ### end Alembic commands ###
